services:
  app:
    build: .
    image: ideanest:latest
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
